### ISSUE TITLE
Can you publish the best numbuer of epoch？

### ISSUE THREAD

**Issue by ZhiyuXu0124** [js-fan/ICD#4]
Hi, Thanks for the great work!<br>
I am trying to reproduce your work.<br>
When I used the default parameters for training:
`python run_icd.py --gpus 0,1 --image-root Your/VOC2012/JPEGImages --annotation-root Your/VOC2012/Annotations --superpixel-root ./data/superpixels/voc_superpixels`
I got only 47% mIoU (with CRF) and 53% mIoU (without CRF). In your paper, mIoU can reach 62.2%. I would like to know some settings of specific parameters. By the way, when I tried to increase the epoch, Code could not generate scores and seeds. I don't know why.

**Comment by js-fan** [comment]
Hi, the reported results are just obtained by the last epoch (20th epoch). I have just re-run the code twice and obtain mIoU 60.2%, 60.3% w/o CRF, and 62.2%, 62.4% w/ CRF, respectively. So, there should be no problem in my environment. Could you share the log file and the detailed per-class mIoU with me to help locate the problem?

**Comment by ZhiyuXu0124** [comment]
Ok, sure
Thank you for your help :)

[vgg16_icd.log](https://github.com/js-fan/ICD/files/5090125/vgg16_icd.log)

**Comment by js-fan** [comment]
Hi, I noticed that you used a small batch size 4, results in only two images per GPU. A small batch size would result in unstable training because of unstable auxiliary statistics. In my original code, the training batch size is 32. Please use a larger batch size and retry it. : )

**Comment by ZhiyuXu0124** [comment]
Appreciate your help!
When I increase the batch size to 32,  I obtain mIoU 59.7% w/o CRF, and 61.5% w/ CRF, respectively.  I think I have used four GPUs, and the batch size should be increased appropriately.
