### ISSUE TITLE
Reproduce the performance using saliency map

### ISSUE THREAD

**Issue by halbielee** [js-fan/ICD#5]
Hello, Junsong Fan! Thank you for sharing your code. 

I am reproducing the performance on your paper. When I trained your code, the pseudo masks are generated well and the performance of them fits well. 

Now I'd like to generate the pseudo mask using the saliency map you used. I get the saliency map from [DSS](https://github.com/Andrew-Qibin/DSS).
How can I integrate the saliency map into the pseudo mask?
In the paper, you mentioned that "replace background score with the saliency scores", but I replace the score with saliency (or 1-saliency) it contain a lot of 'ignore_part'. 

Can you share the details of integrating the saliency map?

Thank you.

**Comment by js-fan** [comment]
Sorry for this delay. I just noticed your message. Your implementation should be right. For saliency-based seeds, we simply use the saliency map to replace the background scores generated by the ICD. The saliency map has high values on salient regions. So to represent the background (or non-salient regions), we should use 1 - S actually. I will update the code to generate seeds with saliency maps later.
