### ISSUE TITLE
Superpixels

### ISSUE THREAD

**Issue by lzyhha** [js-fan/ICD#6]
Hello, thanks for your great work. I want to know the performance when you don't  hierarchically merge the superpixles witch are generated by "Efficient graph-based image segmentation". Could you tell me that?

**Comment by Zhengyang1995** [comment]
Same question. Would you please let us know the performance without superpixels(but with all the rest) thank you so much ~

**Comment by lzyhha** [comment]
这是来自QQ邮箱的自动回复邮件。This is a automatic response.

**Comment by js-fan** [comment]
Hi, thanks for your interest in this work. Our later work shows that the merging strategy is not significant to the performance. We tried the raw superpixels generated by the "Efficient graph-based image segmentation" and the MCG, and the performance fluctuates within 1% mIoU.  But without any superpixels, the performance degrades more than 6%.
