### ISSUE TITLE
The performance without superpixel

### ISSUE THREAD

**Issue by Zhengyang1995** [js-fan/ICD#9]
Hey, thank you for your work.
Would you please let me know the performance with 'Bottom-up' 'Refine' and 'Top-down' but without CRF and superpixel.
I see the performance published in the Table 3 of the paper, the second last one is 59.9%, and you mention there may be a 6% in another closed issue.
Does it mean the performance is around 54% if only superpixel missed?  
Thank you so much for your time~

**Comment by js-fan** [comment]
I appreciate your interest. Based on the experiments, I am sure that the performance will drop without superpixel refinement. However, the exact values can only be obtained after additional experiments. You may clone the code and alter them slightly for that. Feel free to contact me if you encounter any difficulty.

**Comment by Zhengyang1995** [comment]
Okay, thank you so much. I will try.
